repos:
  - repo: local
    hooks:
      - id: prettier
        name: prettier (bun)
        entry: bunx prettier --write
        language: system
        types_or: [javascript, jsx, ts, tsx, json, markdown, css, html, yaml]
        files: \.(js|jsx|ts|tsx|json|md|css|html|ya?ml)$
        pass_filenames: true
