# fly.toml app configuration file generated for pgiant-ultra-bay-wheels-mc on 2025-09-13T16:56:12-07:00
#
# See https://fly.io/docs/reference/configuration/ for information about how to use this file.
#

app = 'pgiant-ultra-bay-wheels-mc'
primary_region = 'sjc'

[build]

[[services]]
  protocol = "tcp"
  internal_port = 8080
  auto_start_machines = true
  auto_stop_machines = "stop"

  [[services.ports]]
    port = 443
    handlers = ["tls"]  # no "http" here
    tls_options = { alpn = ["h2","http/1.1"], versions = ["TLSv1.2","TLSv1.3"] }

[[vm]]
  size = 'shared-cpu-1x'
